#!/usr/bin/env bash
# Displays "Best School" but Hi on 9th iteration

counter=1

while [ $counter -le 11 ]; do
    if [ $counter -eq 10 ]; then
        echo "Hi"
    else   
        echo "Best School"
    fi
    ((counter++))
done 
